#!/usr/bin/env python3

import argparse
import json
import select
import socket
import time
import random
from enum import Enum

BROADCAST = "FFFF"  # the broadcast address
SEED = None  # the seed to use from random number generation (random seed if None)
ELECTION_TIMEOUT_RANGE = range(400, 650)  # the range of values an election timeout will be selected from
HEARTBEAT_FREQUENCY = 175  # the minimum frequency that append RPCs should be sent out from the leader
# the amount of time a leader should wait before assuming it cannot contact a follower
RESPONSE_TIMEOUT = int((ELECTION_TIMEOUT_RANGE.start + ELECTION_TIMEOUT_RANGE.stop) / 2 * 1.5)


class State(Enum):
    """
    Represents one of the three states that a Raft server can be in.
    """

    LEADER = 'leader'
    CANDIDATE = 'candidate'
    FOLLOWER = 'follower'

    def __str__(self):
        """
        Produces a string representing this state for debugging.

        Returns:
            str: the string representing this state
        """

        return self.value


class Entry:
    """
    Represents a put request from a client stored in a Raft server's log.
    """

    def __init__(self, term, key, value, src, dst, mid):
        """
        Constructs a new Entry.

        Args:
            term (int): the term that this entry was added in
            key (str): the key for the state machine
            value (str): the value for the state machine
            src (str): the address of the client sent the request associated with this entry
            dst (str): the address of the leader whom the request associated with this entry was originally sent to
            mid (str): the message ID of the request associated with this entry
        """

        self.term = term
        self.key = key
        self.value = value
        self.src = src
        self.dst = dst
        self.mid = mid

    def encode(self):
        """
        Encodes this entry as a dictionary in order to be sent to another replica.

        Returns:
            dict: the dictionary representing this entry.
        """

        return {'term': self.term,
                'key': self.key,
                'value': self.value,
                'src': self.src,
                'dst': self.dst,
                'mid': self.mid}

    @classmethod
    def decode(cls, dct):
        """
        Constructs a new Entry from a dictionary sent by another replica.

        Args:
            dct (dict): the dictionary containing the data of the entry sent by the other replica

        Returns:
            Entry: the entry constructed from the given dictionary
        """

        return Entry(dct['term'], dct['key'], dct['value'], dct['src'], dct['dst'], dct['mid'])

    def __str__(self):
        return str(self.encode())


class Get:
    """
    Represents a get request from a client.
    """

    def __init__(self, src, key, mid):
        """
        Constructs a new Get.

        Args:
            src (str): the address of the client that made this get request
            key (str): the key corresponding to the value to get from the state machine
            mid (str): the message ID of the get request
        """

        self.src = src
        self.key = key
        self.mid = mid
        self.time = now()

    def __hash__(self):
        """
        Hashes this get based on the message id.

        Returns:
            int: the hash of this Get
        """

        return hash(self.mid)

    def __eq__(self, other):
        """
        Is this Get's message ID equal to another Get's message ID?

        Args:
            other: the other Get to compare to this one

        Returns:
            bool: whether the Gets are equal (True) or not (False)
        """

        return self.mid == other.mid


class Replica:
    """
    Represents this one Raft server.
    """

    def __init__(self, port, id, others):
        """
        Constructs a new Replica.

        Args:
            port (int): the port number to send and receive messages from
            id (int): the ID assigned to this replica
            others (list of str): the IDs of the other replicas in this cluster
        """

        # initialize connection data
        self.port = port
        self.id = id
        self.others = others

        # initialize socket
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('localhost', 0))

        # initialize replica data
        self.state = State.FOLLOWER  # the current state of this replica
        self.log = []  # a list of entries that have or will be added to the state machine
        self.state_machine = {}  # the state machine storing log entries that have been committed
        self.current_term = -1  # the term of this replica
        self.leader = BROADCAST  # the ID of the replica that this replica current believes is the leader
        # how long to wait before staring  an election (in milliseconds)
        self.election_timeout = random.choice(ELECTION_TIMEOUT_RANGE)
        self.app_recv_time = now()  # the last time an append RPC was received
        self.voted_for = None  # the server this replica has voted for during the current term
        self.votes = set()  # the set of replicas that have voted for this replica during the current term
        self.commit_index = -1  # the index of the highest entry that has been committed
        self.gets = set()  # get requests from the client that have not been responded to
        self.maj_thresh = int((len(self.others) + 1) / 2) + 1  # the number of replicas required for a quorum

        # initialize leader data
        # map from IDs to the last time an append RCP was sent to the corresponding server
        self.app_send_times = dict.fromkeys(self.others, now())
        # map from IDs to the index of the highest log entry known to be on the corresponding server
        self.match_index = dict.fromkeys(self.others, -1)
        # map from IDs to next index the leader will send to the corresponding server
        self.next_index = dict.fromkeys(self.others, len(self.log))
        # map from IDs to the last time we've heard from the corresponding server
        self.last_heard = dict.fromkeys(self.others, 0)

        # start a new term
        self.set_term(0)

        # send hello message
        print(f'Replica {self.id} starting up', flush=True)
        self.send_msg(BROADCAST, 'hello', {})

    def run(self):
        """
        Runs this replica, receiving and responding to messages from clients and other servers.
        """

        timeout = self.election_timeout - (now() - self.app_recv_time)  # time to wait before resuming (in ms)

        while True:
            socks = select.select([self.socket], [], [], float(max(0, timeout)) / 1000)[0]
            # handle any messages that were received
            if len(socks) > 0:
                data, addr = socks[0].recvfrom(65535)
                msg = json.loads(data.decode('utf-8'))
                self.handle_msg(msg)

            # check for timeouts
            if self.state == State.LEADER:
                if now() >= min(self.app_send_times.values()) + HEARTBEAT_FREQUENCY:
                    # heartbeat timeout (we haven't sent append RPCs in a while)
                    self.send_heartbeat()
                latest = sorted(self.last_heard.values())[self.maj_thresh - 1]
                if now() >= latest + RESPONSE_TIMEOUT:
                    # leader timeout (we haven't heard form a majority of replicas in a while)
                    self.state = State.FOLLOWER
                    self.leader = BROADCAST
                timeout = min(HEARTBEAT_FREQUENCY - (now() - self.app_recv_time),
                              RESPONSE_TIMEOUT - (now() - latest))
            elif now() >= self.app_recv_time + self.election_timeout:
                # election timeout (we haven't heard from the leader in a while)
                self.begin_election()
                timeout = self.election_timeout - (now() - self.app_recv_time)

    def send_msg(self, dst, type, headers):
        """
        Sends a message to the simulator.

        Args:
            dst (str): the address message's destination
            type (str): the type of the message
            headers (dict): additional headers to add to the message
        """

        msg = {'src': self.id,
               'dst': dst,
               'leader': self.leader,
               'type': type}
        msg.update(headers)
        self.socket.sendto(json.dumps(msg).encode('utf-8'), ('localhost', self.port))

    def send_heartbeat(self):
        """
        Sends an append RCP out to every replica.
        New entries that haven't yet been replicated on other servers will also be sent
        """

        print(f'sending heartbeat', flush=True)
        for dst in self.others:
            self.send_update(dst, force=True)

    def set_term(self, term):
        """
        Updates the current term of this replica if a higher term is provided,
        re-initializing the data for a new term.

        Args:
            term (int): the term to set as this replica's current term
        """

        # increment term
        if term > self.current_term:
            # reinitialize voting data
            self.voted_for = None
            self.election_timeout = random.choice(ELECTION_TIMEOUT_RANGE)
            self.current_term = term

    def begin_election(self):
        """
        Starts a new election by transitioning to candidate state and
        sending vote requests to all other replicas.
        """

        self.set_term(self.current_term + 1)
        print(f'starting election (term: {self.current_term})', flush=True)
        self.app_recv_time = now()
        self.state = State.CANDIDATE
        self.voted_for = self.id
        self.votes = {self.id}  # vote for yourself
        self.leader = BROADCAST

        # send vote requests out to all hosts in cluster
        latest_term = self.log[-1].term if len(self.log) > 0 else -1
        for dst in self.others:
            self.send_msg(dst, 'request_vote', {'term': self.current_term,
                                                'last_log_term': latest_term,
                                                'last_log_index': len(self.log) - 1})

    def commit(self, index):
        """
        Commits all uncommitted log entries up though a given index.

        Args:
            index (int): the index of the highest entry to commit
        """

        # ensure valid index
        if index < self.commit_index:
            return
        else:
            index = min(index, len(self.log) - 1)

        # apply commands to state machine
        for entry in self.log[self.commit_index + 1:index + 1]:
            self.state_machine[entry.key] = entry.value

            # send response to client
            if self.state == State.LEADER:
                self.send_msg(entry.src, 'ok', {'MID': entry.mid})
                print(f'completed PUT (mid: {entry.mid}, key: {entry.key}, value: {entry.value})', flush=True)

        # increment commit index
        self.commit_index = index

    def handle_msg(self, msg):
        """
        Handles the receipt of a new message.

        Args:
            msg (dict): the dictionary representing the decoded message.
        """

        # handlers for different types of messages
        handlers = {'get': self.handle_get,
                    'put': self.handle_put,
                    'request_vote': self.handle_request_vote,
                    'request_vote_response': self.handle_request_vote_response,
                    'append': self.handle_append,
                    'append_response': self.handle_append_response}

        # save the time of hearing from the sender
        if msg['src'] in self.last_heard:
            self.last_heard[msg['src']] = now()

        # call the appropriate handler
        if msg['type'] in handlers.keys():
            handlers[msg['type']](msg)
        else:
            print(f'unknown message type: {msg["type"]}', flush=True)

    def handle_get(self, msg):
        """
        Handles the receipt of a get message.
        Queues the get request, waiting until this replica's data isn't stale before responding.

        Args:
            msg (dict): the decoded get message
        """

        if self.state == State.LEADER:
            # execute the request as the leader
            print(f'executing GET (mid: {msg["MID"]}, key {msg["key"]})', flush=True)
            for dst in self.others:
                self.send_update(dst, force=True)
            self.gets.add(Get(msg['src'], msg['key'], msg['MID']))
        else:
            # redirect request to leader
            print(f'redirecting GET to {self.leader} (mid: {msg["MID"]}, key: {msg["key"]}', flush=True)
            self.send_msg(msg['src'], 'redirect', {'MID': msg['MID']})

    def handle_put(self, msg):
        """
        Handles the receipt of a put message.
        Adds the command to the log and attempts to replicate it on all other server.

        Args:
            msg (dict): the decoded put message
        """

        if self.state == State.LEADER:
            # execute the request as the leader
            if len(list(filter(lambda e: e.mid == msg['MID'], self.log))) > 0:
                # this is a duplicate request, respond immediately
                self.send_msg(msg['src'], 'ok', {'MID': msg['MID']})
            else:
                # this is a new request, add an entry to our log
                print(f'executing PUT (mid: {msg["MID"]}, key {msg["key"]}, '
                       f'value: {msg["value"]}, index: {len(self.log)})', flush=True)
                self.log.append(Entry(self.current_term, msg['key'], msg['value'], msg['src'], msg['dst'], msg['MID']))

                # replicate message on other servers
                for dst in self.others:
                    self.send_update(dst)
        else:
            # redirect request to leader
            print(f'redirecting PUT to {self.leader}', flush=True)
            self.send_msg(msg['src'], 'redirect', {'MID': msg['MID']})

    def handle_request_vote(self, msg):
        """
        Handles the receipt of a request vote RPC
        Votes for the sender if they are more up to date and this replicas hasn't already voted for this term.

        Args:
            msg (dict): the decoded request vote RPC
        """

        # update our current term if we are behind
        self.set_term(msg['term'])

        # ensure this request is valid
        if self.current_term <= msg['term'] and self.voted_for is None and not self.more_updated(msg):
            # vote for the sender
            print(f'voting for {msg["src"]}', flush=True)
            self.state = State.FOLLOWER
            self.leader = BROADCAST
            self.app_recv_time = now()
            self.voted_for = msg['src']
            self.send_msg(msg['src'], 'request_vote_response', {'term': self.current_term})

    def handle_request_vote_response(self, msg):
        """
        Handles the receipt of a request vote response RPC.
        Notes that this replica received a vote from the sender and possibly becomes
        leader if this replica has enough votes.

        Args:
            msg (dict): the decoded request vote response RPC
        """

        # check if we should accept this response
        if self.state == State.CANDIDATE and msg['term'] == self.current_term:
            print(f'received vote from {msg["src"]}', flush=True)
            self.votes.add(msg['src'])

            # check if we have enough votes to win
            if len(self.votes) >= self.maj_thresh:
                # we are the leader now
                print(f"I'm the leader now (term {self.current_term})", flush=True)
                self.state = State.LEADER
                self.leader = self.id
                self.match_index = dict.fromkeys(self.others, -1)
                self.next_index = dict.fromkeys(self.others, len(self.log))

                # notify other servers
                self.send_heartbeat()

    def handle_append(self, msg):
        """
        Handles the receipt of an append RPC.
        Adds new entries to this replica log if the append RPC is valid for this term

        Args:
            msg (dict): the decoded append RPC
        """

        # decode entry objects from dictionary
        entries = list(map(lambda e: Entry.decode(e), msg['entries']))

        # ensure the append RPC is valid for the current term
        if msg['term'] >= self.current_term:
            self.app_recv_time = now()
            self.state = State.FOLLOWER
            self.leader = msg['src']
            self.set_term(msg['term'])

            # check if this RPC contains new entries
            if len(msg['entries']) > 0:
                # ensure our log matches the leader's log up to the new entries
                if msg['prev_log_index'] == -1 or (msg['prev_log_index'] < len(self.log) and
                                                   self.log[msg['prev_log_index']].term == msg['prev_log_term']):
                    # logs match, add entries
                    print(f'adding new {len(entries)} new entries from {msg["src"]}', flush=True)
                    del self.log[msg['prev_log_index'] + 1:len(self.log)]
                    self.log += entries
                    self.commit(msg['leader_commit'])

                    # send response to leader
                    self.send_msg(msg['src'], 'append_response', {'success': True, 'match_index': len(self.log) - 1})
                else:
                    # logs don't match, send a failure message
                    print(f'failed to add new entries from {msg["src"]}', flush=True)
                    self.send_msg(msg['src'], 'append_response', {'success': False})
            else:
                # there are no new entries (this was just a heartbeat message)
                print(f'received empty append message from {msg["src"]}', flush=True)
                self.send_msg(msg['src'], 'append_response', {'success': True, 'match_index': len(self.log) - 1})
                self.commit(msg['leader_commit'])

    def handle_append_response(self, msg):
        """
        Handles the receipt of an append response RPC.
        Notes the entries replicated on the sender on success.
        Retries the append on failure.

        Args:
            msg (dict): the decoded append response RPC
        """

        if msg['success']:
            # entries were successfully added
            print(f'received confirmation that log indices up to {msg["match_index"]} '
                  f'are replicated on {msg["src"]}', flush=True)
            self.match_index[msg['src']] = msg['match_index']
            self.next_index[msg['src']] = msg['match_index'] + 1
            self.apply_safe_entries()
            self.respond_to_gets()
        else:
            # replica failed to add entries, try again with entries further back
            self.next_index[msg['src']] -= 1
            print(f'retrying entry replication on {msg["src"]} with index {self.next_index[msg["src"]]}', flush=True)
            self.send_update(msg['src'])

    def send_update(self, dst, force=False):
        """
        Sends new entries to a destination based on what entries it hasn't already replicated.

        Args:
            dst (str): the address of the server to send this message to
            force (bool): whether to send an empty append RPC if no new entries need to be distributed.
        """

        if self.next_index[dst] <= len(self.log) - 1:
            # there are new entires to send to dst
            print(f'sending entries from index {self.next_index[dst]} to {dst}', flush=True)
            prev_index = self.next_index[dst] - 1
            prev_term = self.log[prev_index].term if prev_index >= 0 else -1
            max_entries = 10
            start_index = prev_index + 1
            end_index = min(prev_index + 1 + max_entries, len(self.log))
            self.send_append(dst, prev_index, prev_term, self.log[start_index:end_index])
        elif force:
            # there are no new entries to send to dst, but we should send a heartbeat
            print(f'sending heartbeat message to {dst}', flush=True)
            self.send_append(dst, None, None, [])

    def send_append(self, dst, prev_index, prev_term, entries):
        """
        Sends and append RPC to the given destination.

        Args:
            dst (str): the address of the server to send this append RPC to
            prev_index (int or None): the index of the log entry immediately before the one being sent
            prev_term (int or NOne): the term of the log entry immediately before the first entry being sent
            entries (list of Entry): the log entries to send in the append RCP
        """

        self.app_send_times[dst] = now()
        self.send_msg(dst, 'append', {'term': self.current_term,
                                      'prev_log_index': prev_index,
                                      'prev_log_term': prev_term,
                                      'entries': list(map(lambda e: e.encode(), entries)),
                                      'leader_commit': self.commit_index})

    def apply_safe_entries(self):
        """
        Commits all entries that have been replicated on a majority of servers and applies
        them to this replica's state machine.
        """

        # find the highest entry we can commit
        highest = self.commit_index
        for index in range(self.commit_index + 1, len(self.log)):
            replications = len(list(filter(lambda n: n >= index, self.match_index.values()))) + 1
            if replications >= self.maj_thresh and self.log[index].term == self.current_term:
                highest = index

        # commit the highest entry we can
        self.commit(highest)

    def respond_to_gets(self):
        """
        Send a response to the client for all get requests that are confirmed do not have stale data.
        """

        # find the latest time that we've heard from the majority of servers
        latest = sorted(self.last_heard.values())[self.maj_thresh - 1]

        # respond to all the get requests after that time (we don't have stale data)
        for get in list(self.gets):
            if get.time <= latest:
                # we can respond to this request
                self.gets.remove(get)

                # send a response to the client
                if get.key in self.state_machine:
                    print(f'completed GET (mid: {get.mid}, key {get.key})', flush=True)
                    self.send_msg(get.src, 'ok', {'MID': get.mid,
                                                  'value': self.state_machine[get.key]})
                else:
                    print(f'can\'t find value for GET (mid: {get.mid}, key {get.key})', flush=True)
                    self.send_msg(get.src, 'ok', {'MID': get.mid,
                                                  'value': ''})

    def more_updated(self, msg):
        """
        Is this replica's log more up to date than another replica's?
        Args:
            msg (dict): a decoded request vote message containing information about the other replica's log

        Returns:
            bool: Whether this replicas log is more up to date (True) or not (False)
        """

        latest_term = self.log[-1].term if len(self.log) > 0 else -1  # the term of the last entry in our log
        return (latest_term, len(self.log) - 1) > (msg['last_log_term'], msg['last_log_index'])


def now():
    """
    Determines the current time.

    Returns:
        int: the current time since the epoch in milliseconds

    """
    return int(time.time() * 1000)



def parse_args():
    """
    Parse the command line arguments for the 3700kvstore program.
    Arguments have the following format:
    ./3700kvstore <UDP port> <your ID> <ID of second replica> [<ID of third replica> ...]]

    Returns:
        argparse.Namespace: the parsed arguments
    """

    parser = argparse.ArgumentParser(description='run a key-value store')
    parser.add_argument('port', type=int, help='Port number to communicate')
    parser.add_argument('id', type=str, help='ID of this replica')
    parser.add_argument('others', metavar='others', type=str, nargs='+', help='IDs of other replicas')
    return parser.parse_args()


# run the kvstore program
if __name__ == '__main__':
    if SEED is not None:
        random.seed(SEED)
    args = parse_args()
    replica = Replica(args.port, args.id, args.others)
    replica.run()
